#%RAML 1.0 DataType
properties:
  passengerId:
    type: string
    required: true
  coachNumber:
    type: string
    required: false
  seatNumber:
    type: integer
    required: false
  classType:
    type: string
    required: true
