#%RAML 1.0 Library
usage: "Data types of errors responses"
types:
  responseBody:
    type: object
    properties:
      "message":
        type: string
        required: true
      "description":
        type: string
        required: true
      "dateTime":
        type: datetime
        required: true
      "transactionId":
        type: string
        required: true